AlquilerBusetas.UI/Models/Buseta.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace AlquilerBusetas.UI.Models
{
    public class Buseta
    {
        [Display(Name = "Id")]
        public long Id { get; set; }
        public string Placa { get; set; }
        [Display(Name = "Cantidad de Pasajeros")]
        public int CantidadPasajeros { get; set; }
        public string Marca { get; set; }
        public EstadoBuseta Estado { get; set; }
        [Display(Name = "Reservado por")]
        public string UsrAsignado { get; set; }
        public decimal Precio { get; set; }
    }
}

AlquilerBusetas.UI/Models/ErrorViewModel.cs
using System;

namespace AlquilerBusetas.UI.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

AlquilerBusetas.UI/Models/EstadoBuseta.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace AlquilerBusetas.UI.Models
{
    public enum EstadoBuseta
    {
        MAL_ESTADO = 0,
        DISPONIBLE = 1,
        OCUPADA = 2
    }
}

AlquilerBusetas.UI/Models/LoginViewModel.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace AlquilerBusetas.UI.Models
{
    public class LoginViewModel
    {
        [Display(Name = "USERNAME")]
        public string UserId { get; set; }
        [Display(Name = "PASSWORD")]
        [DataType(DataType.Password)]
        public string Password { get; set; }
    }
}

AlquilerBusetas.UI/Models/UserSession.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace AlquilerBusetas.UI.Models
{
    public class UserSession
    {
        public string UserCode { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public UserType UserType { get; set; }
        public bool Estado { get; set; }
        public string Telefono { get; set; }
        public byte LoginStatus { get; set; }
    }
}

AlquilerBusetas.UI/Models/UserType.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace AlquilerBusetas.UI.Models
{
    public enum UserType
    {
        ADMIN = 1,
        AGENT = 2,
        CLIENT = 3
    }
}

AlquilerBusetas.UI/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using AlquilerBusetas.UI.Models;
using Microsoft.AspNetCore.Http;
using AlquilerBusetas.UI.Data;
using Microsoft.Extensions.Configuration;

namespace AlquilerBusetas.UI.Controllers
{
    public class HomeController : Controller
    {
        private BusetaDAL dbConnections;
        public HomeController(IConfiguration config )
        {
            dbConnections = new BusetaDAL(config);
        }
        public IActionResult Index()
        {
            if (HttpContext.Session.GetString("UserSession") != null)
            {
                var busetasLista = dbConnections.ListarBusetas(1);
                return View(busetasLista);
            }
            else
            {
                return RedirectToAction("Index", "Login");
            }
        }
        [HttpGet]
        public IActionResult Create()
        {
            if (HttpContext.Session.GetString("UserSession") != null)
            {
                return View();
            }
            else
            {
                return RedirectToAction("Index", "Login");
            }
        }

        [HttpPost]
        public IActionResult Create(Buseta nuevoBuseta)
        {
            if (HttpContext.Session.GetString("UserSession") != null)
            {
                dbConnections.CrearBuseta(nuevoBuseta);
                return RedirectToAction("Index");
            }
            else
            {
                return RedirectToAction("Index", "Login");
            }
        }

        public IActionResult MisBusetas()
        {
            if (HttpContext.Session.GetString("UserSession") != null)
            {
                string userCode = HttpContext.Session.GetString("UserCode");
                var busetasLista = dbConnections.ListarMisBusetas(userCode);
                return View(busetasLista);
            }
            else
            {
                return RedirectToAction("Index", "Login");
            }
        }

        public IActionResult Reservar(int id)
        {
            string userCode = HttpContext.Session.GetString("UserCode");
            dbConnections.EditarBuseta(userCode, id, 2);
            return RedirectToAction("Index");
        }

        public IActionResult Devolver(int id)
        {
            dbConnections.EditarBuseta(string.Empty, id, 1);
            return RedirectToAction("Index");
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

AlquilerBusetas.UI/Controllers/LoginController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AlquilerBusetas.UI.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using AlquilerBusetas.UI.Data;
using Newtonsoft.Json;
using Microsoft.Extensions.Configuration;

namespace AlquilerBusetas.UI.Controllers
{
    public class LoginController : Controller
    {

        private IConfiguration configurationSettings;
        private LoginDAL _dbConnection;

        public LoginController(IConfiguration config)
        {
            this.configurationSettings = config;
            this._dbConnection = new Data.LoginDAL(configurationSettings);
        }
        public IActionResult Index()
        {
            if (HttpContext.Session.GetString("UserSession") != null)
            {

                return RedirectToAction("Index", "Home");
            }
            else
            {
                return View();
            }
        }

        public async Task<ActionResult> Onlogin(Models.LoginViewModel user)
        {
            UserSession userSession = await Task.Run(() => _dbConnection.Login(user));
            // add session to httpcontext
            if (userSession != null)
            {
                if (userSession.LoginStatus == 1)
                {
                    HttpContext.Session.SetString("UserCode", userSession.UserCode);
                    var key = "UserSession";
                    var str = JsonConvert.SerializeObject(userSession);
                    HttpContext.Session.SetString(key, str);
                    return RedirectToAction("Index", "Home");
                }
                else
                {
                    ViewData["ErrorMessage"] = "Invalid user or password";
                    user.UserId = "";
                    return View("~/Views/Login/Index.cshtml");
                }
            }
            else
            {
                ViewData["ErrorMessage"] = "Invalid user or password";
                return View("~/Views/Login/Index.cshtml");
            }
        }

        public ActionResult LogOut()
        {
            HttpContext.Session.Clear();
            return RedirectToAction("Index", "Login");
        }

    }
}

AlquilerBusetas.UI/Controllers/OcupadasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AlquilerBusetas.UI.Data;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;

namespace AlquilerBusetas.UI.Controllers
{
    public class OcupadasController : Controller
    {
        private BusetaDAL dbConnections;
        public OcupadasController(IConfiguration config)
        {
            dbConnections = new BusetaDAL(config);
        }
        // GET: Ocupadas
        public ActionResult Index()
        {
            if (HttpContext.Session.GetString("UserSession") != null)
            {
                var busetasLista = dbConnections.ListarBusetas(2);
                return View(busetasLista);
            }
            else
            {
                return RedirectToAction("Index", "Login");
            }
        }

        // GET: Ocupadas/Edit/5
        public IActionResult Devolver(int id)
        {
            dbConnections.EditarBuseta(string.Empty, id, 1);
            return RedirectToAction("Index");
        }

        
    }
}

AlquilerBusetas.UI/Views/Home/Create.cshtml
@model AlquilerBusetas.UI.Models.Buseta

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Buseta</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Placa" class="control-label"></label>
                <input asp-for="Placa" class="form-control" />
                <span asp-validation-for="Placa" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CantidadPasajeros" class="control-label"></label>
                <input asp-for="CantidadPasajeros" class="form-control" />
                <span asp-validation-for="CantidadPasajeros" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Marca" class="control-label"></label>
                <input asp-for="Marca" class="form-control" />
                <span asp-validation-for="Marca" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Precio" class="control-label"></label>
                <input asp-for="Precio" class="form-control" />
                <span asp-validation-for="Precio" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

AlquilerBusetas.UI/Views/Home/Index.cshtml
@model IEnumerable<AlquilerBusetas.UI.Models.Buseta>

@{
    ViewData["Title"] = "Disponibles";
}

<h1>Busetas Disponibles</h1>

<p>
    <a asp-action="Create">Nueva Buseta</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Placa)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CantidadPasajeros)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Marca)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Estado)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Precio)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.UsrAsignado)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Placa)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CantidadPasajeros)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Marca)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Estado)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Precio)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.UsrAsignado)
            </td>
            <td>
                @Html.ActionLink("Reservar", "Reservar", new { id = item.Id })
            </td>
        </tr>
}
    </tbody>
</table>

AlquilerBusetas.UI/Views/Home/MisBusetas.cshtml
@model IEnumerable<AlquilerBusetas.UI.Models.Buseta>

@{
    ViewData["Title"] = "Mis Busetas";
}

<h1>Mis Busetas</h1>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Placa)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CantidadPasajeros)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Marca)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Estado)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.UsrAsignado)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Placa)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CantidadPasajeros)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Marca)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Estado)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.UsrAsignado)
            </td>
            <td>
                @Html.ActionLink("Devolver", "Devolver", new {  id=item.Id  }) 
            </td>
        </tr>
}
    </tbody>
</table>

AlquilerBusetas.UI/Views/Login/Index.cshtml
@model AlquilerBusetas.UI.Models.LoginViewModel

@{
    ViewData["Title"] = "Login";
}

@{
    Layout = null;
}


<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Login</title>
    <link href="~/lib/bootstrap/dist/css/bootstrap.css" rel="stylesheet" />
    <script src="~/lib/jquery/dist/jquery.js"></script>
    <link href="~/css/style.css" rel="stylesheet" />
    <script src="http://cdn.ckeditor.com/4.6.1/standard/ckeditor.js"></script>
    <script src="~/js/site.js"></script>

</head>
<body>
    <section id="main">
        <div class="container">
            <div class="row d-flex justify-content-center">
                <div class="col-md-4 col-md-offset-4" style="margin-top:10%;">
                    <form asp-action="Onlogin" id="login" class="well">
                        <div class="form-group">
                            <label asp-for="UserId"></label>
                            <input asp-for="UserId" class="form-control" autocomplete="off" id="txtUserId" autofocus required placeholder="Enter Username">
                        </div>
                        <div class="form-group">
                            <label asp-for="Password"></label>
                            <input asp-for="Password" class="form-control" autocomplete="off" required placeholder="Password">
                        </div>
                        <input type="submit" class="btn btn-default btn-block btn-login" id="btnLogin" value="SECURE LOGIN" />
                        <a class="nav-link text-dark" asp-area="" asp-controller="Login" asp-action="SingUp">Sing Up</a>
                        <h4 style="color: red;text-align: center">@ViewData["ErrorMessage"]</h4>
                    </form>
                </div>
            </div>
        </div>
    </section>
    <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
</body>
</html>

AlquilerBusetas.UI/Views/Ocupadas/Index.cshtml
@model IEnumerable<AlquilerBusetas.UI.Models.Buseta>

@{
    ViewData["Title"] = "Index";
}

<h1>Busetas Ocupadas</h1>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Placa)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CantidadPasajeros)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Marca)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Estado)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.UsrAsignado)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Placa)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CantidadPasajeros)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Marca)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Estado)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.UsrAsignado)
            </td>
            <td>
                @Html.ActionLink("Devolver", "Devolver", new {  id=item.Id  }) 
            </td>
        </tr>
}
    </tbody>
</table>

AlquilerBusetas.UI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Alquiler de Busetas</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"/>
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Alquiler de Busetas</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Disponibles</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Ocupadas" asp-action="Index">Ocupadas</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="MisBusetas">Mis Busetas</a>
                        </li>
                    </ul>
                </div>
            </div>
            <div>
                <a class="nav-link text-dark" asp-area="" asp-controller="Login" asp-action="Logout">Log out</a>
            </div>
        </nav>
    </header>
    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - AlquilerBusetas.UI - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>